# Generated by Django 5.2.1 on 2025-06-06 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0002_instrutor_codigo_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='dataNascimento',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 6, 6, 23, 55, 4, 95339, tzinfo=datetime.timezone.utc), help_text='Informe a data de Nascimento', null=True),
        ),
    ]
