# Generated by Django 5.2.1 on 2025-06-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matricula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('datainicial', models.DateField(help_text='Informe a data inicial da matricula')),              
                ('datafinal', models.DateField(help_text='Informe a data final')),
            ],
        ),
    ]
