# Generated by Django 5.2.1 on 2025-06-06 23:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_datafinal_alter_aluno_datainicial'),
        ('instrutor', '0003_alter_instrutor_datanascimento'),
        ('tiposdeatividades', '0002_alter_tipodeatividade_descricao'),
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='codigo_atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='tiposdeatividades.tipodeatividade'),
        ),
        migrations.AddField(
            model_name='turma',
            name='id_instrutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrutores', to='instrutor.instrutor'),
        ),
        migrations.AddField(
            model_name='turma',
            name='matricula_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='aluno.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataFinal',
            field=models.DateField(blank=True, help_text='Informe a data final', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='dataInicial',
            field=models.DateField(default=datetime.datetime(2025, 6, 6, 23, 55, 4, 95339, tzinfo=datetime.timezone.utc), help_text='Informe a data inicial da matricula'),
        ),
    ]
